In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
import matplotlib.pyplot as plt

## #데이터 로드

In [13]:
dam_dispensing = pd.read_excel('Dam dispensing.xlsx', header=[0, 1])
dam_dispensing

      Collect Item:                                                            \
           Wip Line  Process Desc.         Equipment Model.Suffix   Workorder
0           IVI-OB6  Dam Dispenser  Dam dispenser #1  AJX75334501  3F1X5847-2
1           IVI-OB6  Dam Dispenser  Dam dispenser #1  AJX75334501  3F1X5847-2
2           IVI-OB6  Dam Dispenser  Dam dispenser #1  AJX75334501  3F1X5847-2
3           IVI-OB6  Dam Dispenser  Dam dispenser #1  AJX75334501  3F1X5847-2
4           IVI-OB6  Dam Dispenser  Dam dispenser #1  AJX75334501  3F1X5847-2
...             ...            ...               ...          ...         ...
62474       IVI-OB6  Dam Dispenser  Dam dispenser #2  AJX75334505  4F1XB738-1
62475       IVI-OB6  Dam Dispenser  Dam dispenser #1  AJX75334505  4F1XB738-1
62476       IVI-OB6  Dam Dispenser  Dam dispenser #2  AJX75334505  4F1XB738-1
62477       IVI-OB6  Dam Dispenser  Dam dispenser #1  AJX75334505  4F1XB738-1
62478       IVI-OB6  Dam Dispenser  Dam dispenser #2  AJX75334505  4F1XB738-1

                                                                              \
                     LOT ID                Set ID Box ID        Collect Date
0      OP753345013050000002  OP753345013050000002    NaN 2023-05-04 08:57:23
1      OP753345013050000003  OP753345013050000003    NaN 2023-05-04 09:11:35
2      OP753345013050000004  OP753345013050000004    NaN 2023-05-04 09:13:19
3      OP753345013050000005  OP753345013050000005    NaN 2023-05-04 09:15:24
4      OP753345013050000006  OP753345013050000006    NaN 2023-05-04 09:17:27
...                     ...                   ...    ...                 ...
62474  OP753345054040002685  OP753345054040002685    NaN 2024-04-28 18:30:42
62475  OP753345054040002686  OP753345054040002686    NaN 2024-04-28 18:31:43
62476  OP753345054040002687  OP753345054040002687    NaN 2024-04-28 18:32:49
62477  OP753345054040002688  OP753345054040002688    NaN 2024-04-28 18:33:51
62478  OP753345054040002689  OP753345054040002689    NaN 2024-04-28 18:34:57

                     ...    THICKNESS 2                          THICKNESS 3  \
      Insp. Seq No.  ... Collect Result Unit Time Judge Value Collect Result
0                 1  ...            0.0       NaN         NaN            0.0
1                 1  ...            0.0       NaN         NaN            0.0
2                 1  ...            0.0       NaN         NaN            0.0
3                 1  ...            0.0       NaN         NaN            0.0
4                 1  ...            0.0       NaN         NaN            0.0
...             ...  ...            ...       ...         ...            ...
62474             1  ...            0.0       NaN         NaN            0.0
62475             1  ...            0.0       NaN         NaN            0.0
62476             1  ...            0.0       NaN         NaN            0.0
62477             1  ...            0.0       NaN         NaN            0.0
62478             1  ...            0.0       NaN         NaN            0.0

                                  WorkMode
      Unit Time Judge Value Collect Result Unit Time Judge Value Judge Value.1
0           NaN         NaN            7.0       NaN         NaN           NaN
1           NaN         NaN            7.0       NaN         NaN           NaN
2           NaN         NaN            7.0       NaN         NaN           NaN
3           NaN         NaN            7.0       NaN         NaN           NaN
4           NaN         NaN            7.0       NaN         NaN           NaN
...         ...         ...            ...       ...         ...           ...
62474       NaN         NaN            0.0       NaN         NaN           7.0
62475       NaN         NaN            0.0       NaN         NaN           7.0
62476       NaN         NaN            0.0       NaN         NaN           7.0
62477       NaN         NaN            0.0       NaN         NaN           7.0
62478       NaN         NaN            0.0       NaN         NaN           7.0

[62479 rows x 222 columns]

In [14]:
fill1_dispensing = pd.read_excel('Fill1 dispensing.xlsx', header=[0, 1])
fill1_dispensing

      Collect Item:                                                    \
           Wip Line    Process Desc.           Equipment Model.Suffix
0           IVI-OB6  Fill1 Dispenser  Fill1 dispenser #1  AJX75334501
1           IVI-OB6  Fill1 Dispenser  Fill1 dispenser #1  AJX75334501
2           IVI-OB6  Fill1 Dispenser  Fill1 dispenser #1  AJX75334501
3           IVI-OB6  Fill1 Dispenser  Fill1 dispenser #1  AJX75334501
4           IVI-OB6  Fill1 Dispenser  Fill1 dispenser #1  AJX75334501
...             ...              ...                 ...          ...
61923       IVI-OB6  Fill1 Dispenser  Fill1 dispenser #2  AJX75334505
61924       IVI-OB6  Fill1 Dispenser  Fill1 dispenser #1  AJX75334505
61925       IVI-OB6  Fill1 Dispenser  Fill1 dispenser #2  AJX75334505
61926       IVI-OB6  Fill1 Dispenser  Fill1 dispenser #1  AJX75334505
61927       IVI-OB6  Fill1 Dispenser  Fill1 dispenser #2  AJX75334505

                                                                      \
        Workorder                LOT ID                Set ID Box ID
0      3F1X5847-2  OP753345013050000002  OP753345013050000002    NaN
1      3F1X5847-2  OP753345013050000003  OP753345013050000003    NaN
2      3F1X5847-2  OP753345013050000004  OP753345013050000004    NaN
3      3F1X5847-2  OP753345013050000005  OP753345013050000005    NaN
4      3F1X5847-2  OP753345013050000006  OP753345013050000006    NaN
...           ...                   ...                   ...    ...
61923  4F1XB738-1  OP753345054040002685  OP753345054040002685    NaN
61924  4F1XB738-1  OP753345054040002686  OP753345054040002686    NaN
61925  4F1XB738-1  OP753345054040002687  OP753345054040002687    NaN
61926  4F1XB738-1  OP753345054040002688  OP753345054040002688    NaN
61927  4F1XB738-1  OP753345054040002689  OP753345054040002689    NaN

                                         ... Production Qty            \
             Collect Date Insp. Seq No.  ... Collect Result Unit Time
0     2023-05-04 08:59:27             1  ...              1       NaN
1     2023-05-04 09:13:39             1  ...              2       NaN
2     2023-05-04 09:15:42             1  ...              3       NaN
3     2023-05-04 09:17:46             1  ...              4       NaN
4     2023-05-04 09:19:50             1  ...              5       NaN
...                   ...           ...  ...            ...       ...
61923 2024-04-28 18:32:28             1  ...             11       NaN
61924 2024-04-28 18:33:32             1  ...              5       NaN
61925 2024-04-28 18:34:36             1  ...             12       NaN
61926 2024-04-28 18:35:33             1  ...              6       NaN
61927 2024-04-28 18:36:31             1  ...             13       NaN

                       Receip No                             WorkMode  \
      Judge Value Collect Result Unit Time Judge Value Collect Result
0             NaN              1       NaN         NaN              7
1             NaN              1       NaN         NaN              7
2             NaN              1       NaN         NaN              7
3             NaN              1       NaN         NaN              7
4             NaN              1       NaN         NaN              7
...           ...            ...       ...         ...            ...
61923         NaN            435       NaN         NaN              1
61924         NaN            436       NaN         NaN              1
61925         NaN            437       NaN         NaN              1
61926         NaN            438       NaN         NaN              1
61927         NaN            439       NaN         NaN              1


      Unit Time Judge Value Judge Value.1
0           NaN         NaN           NaN
1           NaN         NaN           NaN
2           NaN         NaN           NaN
3           NaN         NaN           NaN
4           NaN         NaN           NaN
...         ...         ...           ...
61923       NaN         NaN           7.0
61924       NaN         NaN           7.0
61925       NaN         NaN           7.0
61926       NaN         NaN           7.0
61927       NaN         NaN           7.0

[61928 rows x 102 columns]

In [15]:
fill2_dispensing = pd.read_excel('Fill2 dispensing.xlsx', header=[0, 1])
fill2_dispensing

      Collect Item:                                                    \
           Wip Line    Process Desc.           Equipment Model.Suffix
0           IVI-OB6  Fill2 Dispenser  Fill2 dispenser #1  AJX75334501
1           IVI-OB6  Fill2 Dispenser  Fill2 dispenser #1  AJX75334501
2           IVI-OB6  Fill2 Dispenser  Fill2 dispenser #1  AJX75334501
3           IVI-OB6  Fill2 Dispenser  Fill2 dispenser #1  AJX75334501
4           IVI-OB6  Fill2 Dispenser  Fill2 dispenser #1  AJX75334501
...             ...              ...                 ...          ...
62313       IVI-OB6  Fill2 Dispenser  Fill2 dispenser #2  AJX75334505
62314       IVI-OB6  Fill2 Dispenser  Fill2 dispenser #1  AJX75334505
62315       IVI-OB6  Fill2 Dispenser  Fill2 dispenser #2  AJX75334505
62316       IVI-OB6  Fill2 Dispenser  Fill2 dispenser #1  AJX75334505
62317       IVI-OB6  Fill2 Dispenser  Fill2 dispenser #2  AJX75334505

                                                                      \
        Workorder                LOT ID                Set ID Box ID
0      3F1X5847-2  OP753345013050000002  OP753345013050000002    NaN
1      3F1X5847-2  OP753345013050000003  OP753345013050000003    NaN
2      3F1X5847-2  OP753345013050000004  OP753345013050000004    NaN
3      3F1X5847-2  OP753345013050000005  OP753345013050000005    NaN
4      3F1X5847-2  OP753345013050000006  OP753345013050000006    NaN
...           ...                   ...                   ...    ...
62313  4F1XB738-1  OP753345054040002685  OP753345054040002685    NaN
62314  4F1XB738-1  OP753345054040002686  OP753345054040002686    NaN
62315  4F1XB738-1  OP753345054040002687  OP753345054040002687    NaN
62316  4F1XB738-1  OP753345054040002688  OP753345054040002688    NaN
62317  4F1XB738-1  OP753345054040002689  OP753345054040002689    NaN

                                         ... Production Qty            \
             Collect Date Insp. Seq No.  ... Collect Result Unit Time
0     2023-05-04 09:00:48             1  ...              1       NaN
1     2023-05-04 09:15:00             1  ...              2       NaN
2     2023-05-04 09:17:04             1  ...              3       NaN
3     2023-05-04 09:19:08             1  ...              4       NaN
4     2023-05-04 09:21:11             1  ...              5       NaN
...                   ...           ...  ...            ...       ...
62313 2024-04-28 18:33:41             1  ...             11       NaN
62314 2024-04-28 18:34:43             1  ...              5       NaN
62315 2024-04-28 18:35:50             1  ...             12       NaN
62316 2024-04-28 18:36:34             1  ...              6       NaN
62317 2024-04-28 18:37:38             1  ...             13       NaN

                       Receip No                             WorkMode  \
      Judge Value Collect Result Unit Time Judge Value Collect Result
0             NaN              1       NaN         NaN              0
1             NaN              1       NaN         NaN              0
2             NaN              1       NaN         NaN              0
3             NaN              1       NaN         NaN              0
4             NaN              1       NaN         NaN              0
...           ...            ...       ...         ...            ...
62313         NaN            435       NaN         NaN              1
62314         NaN            436       NaN         NaN              1
62315         NaN            437       NaN         NaN              1
62316         NaN            438       NaN         NaN              1
62317         NaN            439       NaN         NaN              1


      Unit Time Judge Value Judge Value.1
0           NaN         NaN           NaN
1           NaN         NaN           NaN
2           NaN         NaN           NaN
3           NaN         NaN           NaN
4           NaN         NaN           NaN
...         ...         ...           ...
62313       NaN         NaN           0.0
62314       NaN         NaN           0.0
62315       NaN         NaN           0.0
62316       NaN         NaN           0.0
62317       NaN         NaN           0.0

[62318 rows x 132 columns]

In [16]:
auto_clave = pd.read_excel('Auto clave.xlsx', header=[0, 1])
auto_clave

      Collect Item:                                                           \
           Wip Line   Process Desc.       Equipment Model.Suffix   Workorder
0           IVI-OB6  Auto Clave Out  Auto Clave Out  AJX75334501  3F1X5847-2
1           IVI-OB6  Auto Clave Out  Auto Clave Out  AJX75334501  3F1X5847-2
2           IVI-OB6  Auto Clave Out  Auto Clave Out  AJX75334501  3F1X5847-2
3           IVI-OB6  Auto Clave Out  Auto Clave Out  AJX75334501  3F1X5847-2
4           IVI-OB6  Auto Clave Out  Auto Clave Out  AJX75334501  3F1X5847-2
...             ...             ...             ...          ...         ...
61047       IVI-OB6  Auto Clave Out  Auto Clave Out  EAT65200901  4EPM0222-2
61048       IVI-OB6  Auto Clave Out  Auto Clave Out  EAT65200901  4EPM0222-2
61049       IVI-OB6  Auto Clave Out  Auto Clave Out  EAT65200901  4EPM0222-2
61050       IVI-OB6  Auto Clave Out  Auto Clave Out  EAT65200901  4EPM0222-2
61051       IVI-OB6  Auto Clave Out  Auto Clave Out  EAT65200901  4EPM0222-2

                                                                              \
                     LOT ID                Set ID Box ID        Collect Date
0      OP753345013050000002  OP753345013050000002    NaN 2023-05-04 09:29:00
1      OP753345013050000003  OP753345013050000003    NaN 2023-05-04 09:49:12
2      OP753345013050000004  OP753345013050000004    NaN 2023-05-04 09:49:12
3      OP753345013050000005  OP753345013050000005    NaN 2023-05-04 09:49:12
4      OP753345013050000006  OP753345013050000006    NaN 2023-05-04 09:49:12
...                     ...                   ...    ...                 ...
61047  OP652009014040000066  OP652009014040000066    NaN 2024-04-20 12:03:45
61048  OP652009014040000067  OP652009014040000067    NaN 2024-04-20 12:03:45
61049  OP652009014040000068  OP652009014040000068    NaN 2024-04-20 11:52:26
61050  OP652009014040000069  OP652009014040000069    NaN 2024-04-20 11:52:26
61051  OP652009014040000070  OP652009014040000070    NaN 2024-04-20 11:42:24

                     ... 2nd Pressure   3rd Pressure                        \
      Insp. Seq No.  ...  Judge Value Collect Result Unit Time Judge Value
0                 1  ...           OK          0.503        90          OK
1                 1  ...           OK          0.501        90          OK
2                 1  ...           OK          0.501        90          OK
3                 1  ...           OK          0.501        90          OK
4                 1  ...           OK          0.501        90          OK
...             ...  ...          ...            ...       ...         ...
61047             1  ...           OK          0.499       120          OK
61048             1  ...           OK          0.499       120          OK
61049             1  ...           OK          0.500       120          OK
61050             1  ...           OK          0.500       120          OK
61051             1  ...           OK          0.498       120          OK

       Chamber Temp.                       GMES_ORIGIN_INSP_JUDGE_CODE  \
      Collect Result Unit Time Judge Value              Collect Result
0                 56       510          OK                         NaN
1                 50       510          OK                         NaN
2                 50       510          OK                         NaN
3                 50       510          OK                         NaN
4                 50       510          OK                         NaN
...              ...       ...         ...                         ...
61047             35       360          OK                         NaN
61048             35       360          OK                         NaN
61049             36       360          OK                         NaN
61050             36       360          OK                         NaN
61051             36       360          OK                         NaN


      Unit Time Judge Value
0           NaN         NaN
1           NaN         NaN
2           NaN         NaN
3           NaN         NaN
4           NaN         NaN
...         ...         ...
61047       NaN         NaN
61048       NaN         NaN
61049       NaN         NaN
61050       NaN         NaN
61051       NaN         NaN

[61052 rows x 26 columns]

In [17]:
train_y = pd.read_csv('train_y.csv')
train_y

                     Set ID    target
0      OP753345013050000003  AbNormal
1      OP753345013050000004  AbNormal
2      OP753345013050000007  AbNormal
3      OP753345013050000011  AbNormal
4      OP753345013050000024  AbNormal
...                     ...       ...
40501  OP753345054040002680    Normal
40502  OP753345054040002681    Normal
40503  OP753345054040002682    Normal
40504  OP753345054040002684    Normal
40505  OP753345054040002688    Normal

[40506 rows x 2 columns]

In [19]:
# 열 이름을 단일 레벨로 변환 ('Set ID'는 두 개의 레벨 중 첫 번째 레벨)
def flatten_columns(df):
    df.columns = ['_'.join(col).strip() for col in df.columns.values]
    return df

auto_clave = flatten_columns(auto_clave)
dam_dispensing = flatten_columns(dam_dispensing)
fill1_dispensing = flatten_columns(fill1_dispensing)
fill2_dispensing = flatten_columns(fill2_dispensing)

In [25]:
fill2_dispensing

,Collect Item:_Wip Line,Collect Item:_Process Desc.,Collect Item:_Equipment,Collect Item:_Model.Suffix,Collect Item:_Workorder,Collect Item:_LOT ID,Collect Item:_Set ID,Collect Item:_Box ID,Collect Item:_Collect Date,Collect Item:_Insp. Seq No.,...,Production Qty_Collect Result,Production Qty_Unit Time,Production Qty_Judge Value,Receip No_Collect Result,Receip No_Unit Time,Receip No_Judge Value,WorkMode_Collect Result,WorkMode_Unit Time,WorkMode_Judge Value,WorkMode_Judge Value.1
0,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000002,OP753345013050000002,NaN,2023-05-04 09:00:48,1,...,1,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
1,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000003,OP753345013050000003,NaN,2023-05-04 09:15:00,1,...,2,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
2,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000004,OP753345013050000004,NaN,2023-05-04 09:17:04,1,...,3,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
3,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000005,OP753345013050000005,NaN,2023-05-04 09:19:08,1,...,4,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
4,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #1,AJX75334501,3F1X5847-2,OP753345013050000006,OP753345013050000006,NaN,2023-05-04 09:21:11,1,...,5,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62313,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002685,OP753345054040002685,NaN,2024-04-28 18:33:41,1,...,11,NaN,NaN,435,NaN,NaN,1,NaN,NaN,0.0
62314,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002686,OP753345054040002686,NaN,2024-04-28 18:34:43,1,...,5,NaN,NaN,436,NaN,NaN,1,NaN,NaN,0.0
62315,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002687,OP753345054040002687,NaN,2024-04-28 18:35:50,1,...,12,NaN,NaN,437,NaN,NaN,1,NaN,NaN,0.0
62316,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #1,AJX75334505,4F1XB738-1,OP753345054040002688,OP753345054040002688,NaN,2024-04-28 18:36:34,1,...,6,NaN,NaN,438,NaN,NaN,1,NaN,NaN,0.0
62317,IVI-OB6,Fill2 Dispenser,Fill2 dispenser #2,AJX75334505,4F1XB738-1,OP753345054040002689,OP753345054040002689,NaN,2024-04-28 18:37:38,1,...,13,NaN,NaN,439,NaN,NaN,1,NaN,NaN,0.0

In [26]:
data = auto_clave.merge(dam_dispensing, on='Collect Item:_Set ID', suffixes=('_auto_clave', '_dam_dispensing'))
data = data.merge(fill1_dispensing, on='Collect Item:_Set ID', suffixes=('', '_fill1_dispensing'))
data = data.merge(fill2_dispensing, on='Collect Item:_Set ID', suffixes=('', '_fill2_dispensing'))

In [27]:
data

,Collect Item:_Wip Line_auto_clave,Collect Item:_Process Desc._auto_clave,Collect Item:_Equipment_auto_clave,Collect Item:_Model.Suffix_auto_clave,Collect Item:_Workorder_auto_clave,Collect Item:_LOT ID_auto_clave,Collect Item:_Set ID,Collect Item:_Box ID_auto_clave,Collect Item:_Collect Date_auto_clave,Collect Item:_Insp. Seq No._auto_clave,...,Production Qty_Collect Result_fill2_dispensing,Production Qty_Unit Time_fill2_dispensing,Production Qty_Judge Value_fill2_dispensing,Receip No_Collect Result_fill2_dispensing,Receip No_Unit Time_fill2_dispensing,Receip No_Judge Value_fill2_dispensing,WorkMode_Collect Result_fill2_dispensing,WorkMode_Unit Time_fill2_dispensing,WorkMode_Judge Value_fill2_dispensing,WorkMode_Judge Value.1_fill2_dispensing
0,IVI-OB6,Auto Clave Out,Auto Clave Out,AJX75334501,3F1X5847-2,OP753345013050000002,OP753345013050000002,NaN,2023-05-04 09:29:00,1,...,1,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
1,IVI-OB6,Auto Clave Out,Auto Clave Out,AJX75334501,3F1X5847-2,OP753345013050000003,OP753345013050000003,NaN,2023-05-04 09:49:12,1,...,2,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
2,IVI-OB6,Auto Clave Out,Auto Clave Out,AJX75334501,3F1X5847-2,OP753345013050000004,OP753345013050000004,NaN,2023-05-04 09:49:12,1,...,3,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
3,IVI-OB6,Auto Clave Out,Auto Clave Out,AJX75334501,3F1X5847-2,OP753345013050000005,OP753345013050000005,NaN,2023-05-04 09:49:12,1,...,4,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
4,IVI-OB6,Auto Clave Out,Auto Clave Out,AJX75334501,3F1X5847-2,OP753345013050000006,OP753345013050000006,NaN,2023-05-04 09:49:12,1,...,5,NaN,NaN,1,NaN,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113018,IVI-OB6,Auto Clave Out,Auto Clave Out,AJX75334507,4CPXX084-0001,OP753345074030000006,OP753345074030000006,NaN,2024-03-26 18:27:20,1,...,7,NaN,NaN,267,NaN,NaN,1,NaN,NaN,0.0
113019,IVI-OB6,Auto Clave Out,Auto Clave Out,AJX75334507,4CPXX084-0001,OP753345074030000007,OP753345074030000007,NaN,2024-03-26 18:27:20,1,...,8,NaN,NaN,268,NaN,NaN,1,NaN,NaN,0.0
113020,IVI-OB6,Auto Clave Out,Auto Clave Out,AJX75334507,4CPXX084-0001,OP753345074030000008,OP753345074030000008,NaN,2024-03-26 18:27:19,1,...,1,NaN,NaN,269,NaN,NaN,1,NaN,NaN,0.0
113021,IVI-OB6,Auto Clave Out,Auto Clave Out,AJX75334507,4CPXX084-0001,OP753345074030000009,OP753345074030000009,NaN,2024-03-26 18:27:20,1,...,2,NaN,NaN,270,NaN,NaN,1,NaN,NaN,0.0
113022,IVI-OB6,Auto Clave Out,Auto Clave Out,AJX75334507,4CPXX084-0001,OP753345074030000010,OP753345074030000010,NaN,2024-03-26 18:27:20,1,...,3,NaN,NaN,271,NaN,NaN,1,NaN,NaN,0.0

In [31]:
# 'Collect Item:_Set ID' 열에서 고유 값 개수 확인
unique_values = data['Collect Item:_Set ID'].unique()
print(f"Unique values count: {len(unique_values)}")

# 중복된 값의 개수 확인
duplicates_count = data['Collect Item:_Set ID'].duplicated().sum()
print(f"Number of duplicated values: {duplicates_count}")

Unique values count: 57867
Number of duplicated values: 55156

In [29]:
duplicate_values = data[data.duplicated(subset=['Collect Item:_Set ID'], keep=False)]
print(duplicate_values[['Collect Item:_Set ID']])

        Collect Item:_Set ID
30      OP753345013050000045
31      OP753345013050000045
32      OP753345013050000045
33      OP753345013050000045
34      OP753345013050000045
...                      ...
112918  OP753345064040000021
112919  OP753345064040000021
112920  OP753345064040000021
112921  OP753345064040000021
112922  OP753345064040000021

[58119 rows x 1 columns]

In [ ]:
# 결측치 처리 (예: 평균값 대체)
data.fillna(data.mean(), inplace=True)

In [ ]:
# 피쳐와 타겟 분리
X = data.drop(columns=['Set ID', 'target'])
y = data['target']

# 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=110)

In [ ]:
# 랜덤 포레스트 모델 학습
model = RandomForestClassifier(random_state=110)
model.fit(X_train, y_train)

# 예측 및 평가
y_pred = model.predict(X_test)
print(f"F1 Score: {f1_score(y_test, y_pred, pos_label='AbNormal')}")

# 피쳐 중요도 시각화
importances = model.feature_importances_
indices = np.argsort(importances)[::-1]

plt.figure(figsize=(12, 8))
plt.title("Feature Importances")
plt.bar(range(X.shape[1]), importances[indices], align="center")
plt.xticks(range(X.shape[1]), X.columns[indices], rotation=90)
plt.xlim([-1, X.shape[1]])
plt.show()